name: Practice GitHub Actions with Python Application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uvicorn fastapi pydantic PyJWT

    - name: Check versions
      run: |
        python --version
        pip --version
        uvicorn --version

    - name: Run Tests
      run: |
        cd src
        uvicorn main:app --host 0.0.0.0 --port 8000 &
        sleep 5  # Wait for the server to start
        # You can add your test commands here, like pytest, curl, or http requests.
        kill $!  # Stop the server after the tests
