name: Practice GitHub Actions with Python Application
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]

    steps:
    - uses: actions/checkout@v3
    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip --version
        pip install uvicorn
        uvicorn --version
        pip install PyJWT
        pip install fastapi
        pip install pydantic


    - name: Run Tests
      run: |
        cd src
        uvicorn main:app --reload
        
