apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectzero
  namespace: default
  labels:
    app: zero
    type: backend
spec:
  template:
    metadata:
      name: projectzero
      labels:
        app: zero
        type: backend
    spec:
      containers:
      - name: projectzero
      image: bhargavpetlu1434/newprojectzero
      ports:
      - containerPort: 8000
  replicas: 2
  selector:
    matchLabels:
      app: zero
