apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
      image: bhargavpetlu1434/newproject
      ports:
      - containerPort: 8000
