apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectzero
  namespace: default
  labels:
    app: zero
    type: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zero
      type: backend
  template:
    metadata:
      labels:
        app: zero
        type: backend
    spec:
      containers:
      - name: projectzero
        image: bhargavpetlu1434/projectzerorepo
        ports:
        - containerPort: 8000